### PR TITLE
changed View::factory to View::forge

### PR DESCRIPTION
**Pull request by loganville**
Updated to work with Fuel 1.5

### CODE REVIEW

**Comment by vrcAlbert** [comment]
Hi, I "need" this too. It's been nine month, is there any way to accelerate the process?

**Comment by fuel-packages** [comment]
Nobody watches these repo's, 

The idea behind it was to use it as a central store for Fuel packages, where the owners of the packages have write access to their packages, and maintain them themselfs. But obviously that doesn't seem to work.

**Comment by emlynwest** [comment]
And given the rise of composer repos like this are even less used than before.

**Comment by sdrdis** [comment]
Ok thanks :+1:. @stevewest Concerning the use of composer and fuel-packages, do you plan to change how the packages are downloaded when executing:

```
php oil package install test-package
```

or will it still download them using git ?

**Comment by emlynwest** [comment]
I don't think the way fuel packages will change, given that v2 is "around the corner".

**Pull request merged**
